# Default values for mojaloop-musoni-core-connector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: pm4ml/musoni-pm4ml-core-connector
  tag: 1.1.0
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

#### ENV values
env:
# this is the outbound api endpoint on the mojaloop-connector
  MLCONN_OUTBOUND_ENDPOINT: http://localhost:4001
  # these are for the DFSP core (CBS) connection details
  DFSP_HOST: ""
  DFSP_USERNAME: ""
  DFSP_PASSWORD: ""
  DFSP_AUTH_TENANT_ID: ""
  DFSP_AUTH_CHANNEL_ID: ""
  DFSP_AUTH_API_KEY: ""
service:
  type: ClusterIP
  # this is the port the SERVICE will listen on. requests to the service address on this port
  # get mapped to the "http" named port on the deployment
  port: 3003

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
