apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pm4ml-management-api-service.fullname" . }}
  labels:
{{ include "pm4ml-management-api-service.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pm4ml-management-api-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pm4ml-management-api-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.imagePullCredentials }}
      imagePullSecrets:
        - name: {{ include "pm4ml-management-api-service.fullname" . }}-cred
      {{- end }}
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DFSP_ID
              value: {{ .Values.env.dfspId | quote }}
            - name: ENV_ID
              value: {{ .Values.env.envId | quote }}
            - name: MCM_SERVER_ENDPOINT
              value: {{ .Values.env.mcmServerEndpoint | quote }}
            - name: MCM_CLIENT_REFRESH_INTERVAL
              value: {{ .Values.env.mcmClientRefreshInterval | quote }}
            - name: MCM_CLIENT_SECRETS_LOCATION
              value: {{ .Values.env.mcmClientsSecretsLocation | quote }}
            - name: MCM_API_TOKEN
              value: {{ .Values.env.mcmAPIToken | quote }}
            - name: PEER_ENDPOINT
              value: {{ .Values.env.peer_endpoint | quote }}
            - name: CACHE_HOST
              value: {{ .Values.env.cache_host | quote }}
            - name: TLS_SERVER_PRIVATE_KEY
              value: {{ .Values.env.tlsServerPvtKeyPath | quote }}
            - name: DFSP_CA_PATH
              value: {{ .Values.env.tlsServerCAPath | quote }}
            - name: PRIVATE_KEY_LENGTH
              value: {{ .Values.env.dfspCsrPrivateKeyLength | quote }}
            - name: PRIVATE_KEY_ALGORITHM
              value: {{ .Values.env.dfspCsrPrivateKeyAlgorithm | quote }}
            - name: WS_URL
              value: {{ .Values.env.wsUrl | quote }}
            - name: WS_PORT
              value: {{ .Values.env.wsPort | quote }}
            - name: DFSP_CLIENT_CSR_PARAMETERS
              value: {{ .Values.env.tlsClientCSRParametersPath | quote }}
            - name: DFSP_SERVER_CSR_PARAMETERS
              value: {{ .Values.env.tlsServerCSRParametersPath | quote }}
            - name: VAULT_ENDPOINT
              value: {{ .Values.env.vault.endpoint | quote }}
            - name: VAULT_AUTH_METHOD
              value: {{ .Values.env.vault.auth.method | quote }}
            - name: VAULT_K8S_ROLE
              value: {{ .Values.env.vault.auth.k8s.role | quote }}
            - name: VAULT_K8S_TOKEN_FILE
              value: {{ .Values.env.vault.auth.k8s.tokenFile | quote }}
            - name: VAULT_ROLE_ID_FILE
              value: {{ .Values.env.vault.auth.appRole.roleId | quote }}
            - name: VAULT_ROLE_SECRET_ID_FILE
              value: {{ .Values.env.vault.auth.appRole.secretId | quote }}
            - name: VAULT_PKI_BASE_DOMAIN
              value: {{ .Values.env.vault.pkiBaseDomain | quote }}
            - name: VAULT_MOUNT_PKI
              value: {{ .Values.env.vault.mount.pki | quote }}
            - name: VAULT_MOUNT_KV
              value: {{ .Values.env.vault.mount.kv | quote }}

            {{- range $key, $val := .Values.env }}
            - name: {{$key}}
              value: {{$val | quote}}
            {{- end}}
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          volumeMounts:
          - mountPath: /secrets
            name: secret-volume
          - mountPath: /tls
            name: tls-secret
          - mountPath: /resources
            name: tls-configmap
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: secret-volume
        emptyDir: {}
      - name: tls-secret
        secret:
            secretName: {{ include "pm4ml-management-api-service.fullname" . }}-tls-secret
      - name: tls-configmap
        configMap:
            name: {{ include "pm4ml-management-api-service.fullname" . }}-tls-configmap
            items:
            - key: tlsClientCSRParameters.json
              path: tlsClientCSRParameters.json
            - key: tlsServerCSRParameters.json
              path: tlsServerCSRParameters.json
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
